### ISSUE TITLE
GCP support

### ISSUE THREAD

**Issue by djKooks** [AlloyCI/alloy_ci#256]
Hello,
first, thanks for your great work 😆 

Seems that it uses AWS for storage. Do you have plan for GCP support?

Thanks.

**Comment by supernova32** [comment]
Hi @djKooks. There is no specific support for GCP planned, however, the storage engine is not AWS specific. It can be used with any S3 compatible storage engine. On https://alloy-ci.com this engine is a Minio instance. I'm sure it can also be used with GCP if it is fully S3 compliant. Have a look at the documentation for S3 storage here: https://github.com/AlloyCI/alloy_ci/tree/master/doc#s3-storage-configuration
