### ISSUE TITLE
Frontend compilation not working for development

### ISSUE THREAD

**Issue by mindreframer** [AlloyCI/alloy_ci#37]
Hey @supernova32, first of all: thank you for this project, really liking many decisions you took for alloy_ci! 

I am somewhat confused by having different output from docker build compared to my local development environment (osx). 

## Output Docker build
![image](https://user-images.githubusercontent.com/1232/36528198-967cc652-17b4-11e8-8f94-743b13fa0595.png)

## same code on OSX, not properly compiling
![image](https://user-images.githubusercontent.com/1232/36528260-bf2e7c08-17b4-11e8-8689-d2aa6917b66c.png)

Also, when I comment out normalize, there are lots of other CSS issues. And some NPM packages are missing, like tether / popper.js. I wonder if you have some extra configs locally, that are not committed to Git for local development.

Could you shine some light on this?

**Comment by supernova32** [comment]
Hi @mindreframer! Thanks for your comments!

I'm not entirely sure about why the output is different between Docker and your local environment, but my guess is that the Docker build runs for the `prod` environment and your are running in `dev` locally.

If your are trying to build AlloyCI in a `prod` environment for macOS, have a look at the `Dockerfile.build` and all the commands it performs **before** creating the build (I just realized these steps are missing from the manual installation section of the docs, thanks for pointing it out!)

If you are trying to run it in `dev`, you might need to run `cd assets/ && npm install` before running `mix phx.server`.

Let me know if this helps. I'll be updating the docs to fix this right away.

**Comment by mindreframer** [comment]
Hey, thx for the response. I installed npm packages before, still brunch
spits out the error. But ok, it is not that critical. I just thought that
there was something else I was missing. Off-topic: Do you still plan to
remove core.ui?

**Comment by supernova32** [comment]
Since you are in `dev`, then there should be no need to run the `brunch` commands. These are run by Phoenix whenever you start `mix phx.server` in the `dev` environment.

Re: core-ui. I would like to have something custom made for AlloyCI, but I am not a designer, or a frontend dev, so it would look really ugly if I attempt that on my own 😛. So it will stay there for the time being.

**Comment by mindreframer** [comment]
Alright, thx! I ran the command just to demonstrate  it outside of Phoenix. 


Re: ui. You should try a combination of https://picturepan2.github.io/spectre + tachyons.io. Just including the minified files without further customisation should be simple and would already look good.   Reproducing the current UI should not too much trouble and you would get rid of bootstrap + the custom build step. 


Here are some links for tachyons: 

Tachyons:
  - http://tachyons.io/
  - https://tachyons-tldr.now.sh/#/classes
  - https://code.luasoftware.com/tutorials/web-development/tachyon-css-cheatsheet/
  - https://github.com/dwyl/learn-tachyons

  - https://egghead.io/lessons/css-design-for-mobile-first-with-tachyons
  - https://egghead.io/lessons/css-build-responsive-css-layouts-with-tachyons

  - https://hackernoon.com/full-re-write-with-tachyons-and-functional-css-a-case-study-part-1-635ccb5fb00b
  - https://medium.com/@Markjobrien/my-experience-with-tachyons-css-so-far-8f63b41eb14b - My experience with Tachyons CSS (so far)
  - https://www.liquidint.com/blog/my-favorite-tools-for-design-tachyons-css-toolkit/#

Cheers and good luck!

**Comment by supernova32** [comment]
Thanks for the resources. I'll definitely check them out.
