### ISSUE TITLE
https://alloy-ci.com/ is returning 502

### ISSUE THREAD

**Issue by natecox** [AlloyCI/alloy_ci#42]
Thought you'd like to know that your site is returning a 502.

![image](https://user-images.githubusercontent.com/2782695/37625672-22578390-2b8a-11e8-83f7-415ab9f178f0.png)

**Comment by supernova32** [comment]
Thanks for the heads up. Digital Ocean rebooted the host to patch some Spectre stuff, and I haven't set up auto-start yet. It is fixed now.
